### ISSUE TITLE
Your Info - User can skip required fields

### ISSUE THREAD

**Issue by joeyqa** [tooldigital/pandora-sly-p2#1]
Only the down arrow is disabled when the required fields are empty. As a result, the user can click/tap the button label to skip entering the required fields.

**Expected Result:**
- The button label should be disabled as well.

**Browser / Device info:**
- All desktop browsers

**URL:**
- http://soundslikeyoudev.seethroughlab.com

**Steps:**
1. Load the URL.
2. Tap the down arrow button.
3. Tap the button label beside the disabled down arrow.
4. Verify that the user can skip the required fields.

Please see the following video: https://goo.gl/Z1jtoz

**Comment by wearenocomputer** [comment]
Please re-test/validate again...

**Comment by jonathanschaefferhookqa** [comment]
Verified Fixed, valid entries now need to be entered before the user continues with the experience.
