### ISSUE TITLE
IE11 - The site didn't load properly

### ISSUE THREAD

**Issue by joeyqa** [tooldigital/pandora-sly-p2#10]
**Expected Result:**
- Is IE11 supported?

**Browser / Device info:**
- Windows 10 - IE11
- Windows 8.1 - IE11

**URL:**
- http://soundslikeyoudev.seethroughlab.com/#!/your-info

**Steps:**
1. Load the URL.
2. Verify that the site didn't load properly in IE.

Please see the attached screenshot(s): https://goo.gl/6EnuM4

**Comment by wearenocomputer** [comment]
Please re-test/validate...

**Comment by stewartwarner** [comment]
It appears to be loading now
