### ISSUE TITLE
Safari - Circle button shifts up on mouse hover

### ISSUE THREAD

**Issue by joeyqa** [tooldigital/pandora-sly-p2#11]
Adding a new tab to safari browser makes the "continue" button of the site to shift up when hovered.

**Expected Result:**
- The position should be fixed.

**Browser / Device info:**
- Macbook 10.13 - Safari 11

**URL:**
- http://soundslikeyoudev.seethroughlab.com/

**Steps:**
1. Load the URL.
2. Add a new tab to the browser.
3. Return to Pandora's tab.
4. Hover on the Continue button below.
5. Verify that the button shifts up when hovered.

Please see the following video: https://goo.gl/tTaWpp

**Comment by wearenocomputer** [comment]
Unable to reproduce on my end (Mac Book Pro 10.13 - Safari 11.3).
Super weird issue... (also: seems like an ultra-edge-case)

@joeyqa Can you test this again?

**Comment by jonathanschaefferhookqa** [comment]
I can't reproduce the issue above however on smaller screens / breakpoints this can cause the Down arrow and line to intersect with each other.

Video Example: https://drive.google.com/file/d/0B4Hu_FkAehL4c3RYMEZKc3NTNVk/view?usp=sharing

**Comment by wearenocomputer** [comment]
@jonathanschaefferhookqa 
I've just deployed an update with some tweaks. 
Sorry to bother, but could you check once more?

**Comment by jonathanschaefferhookqa** [comment]
Verified fixed, the new push has resolved both of these issues.
