### ISSUE TITLE
Change homepage copy to what is on soundslikeyou.pandora.com.

### ISSUE THREAD

**Issue by jeankcha** [tooldigital/pandora-sly-p2#12]
<img width="1155" alt="screen shot 2018-06-15 at 9 23 39 am" src="https://user-images.githubusercontent.com/20075652/41478830-fca73f08-707d-11e8-9b1f-f97d60f66f80.png">

**Comment by wearenocomputer** [comment]
Please re-test/validate again...

**Comment by jonathanschaefferhookqa** [comment]
The paragraph on dev matches the live site however there are a few labels on the homepage that do not match.

Your Personal Brand Sonic Identity Generator (Dev)
Sounds Like You (Live)

Tap to Begin (Dev)
Scroll to Begin (Live)

**Comment by wearenocomputer** [comment]
@jeankcha 
The title "Your Personal Brand Sonic Identity Generator" is taken from the designs I received.

"Tap to Begin" (Dev) vs. "Scroll to Begin" (Live)
I've changed this since we removed the scrolling gestures.

**Comment by jeankcha** [comment]
Received confirmation from David he wants the title and block of copy to match the original site. "Sounds Like You."

**Comment by wearenocomputer** [comment]
Please re-test/validate...

**Comment by lfm5002** [comment]
Page title is verified as sounds Like You
