### ISSUE TITLE
Your Songs - Songs with long text details overlaps the mixed it up button

### ISSUE THREAD

**Issue by joeyqa** [tooldigital/pandora-sly-p2#2]
Song details below the artist's name sometimes overlap the MIX IT UP button when the site is viewed on desktops with smaller viewports around 1366x768 and also in MacBook Pro (Retina) 13-inch screen.

**Expected Result:**
- Adjust button position lower.

**Browser / Device info:**
- All desktop browsers

**URL:**
- http://soundslikeyoudev.seethroughlab.com

**Steps:**
1. Load the URL.
2. Go through the process up to Your Songs selection page.
3. Click the MIX IT UP button multiple times.
4. Verify that there are songs with long details that overlaps the MIX IT UP button.

Please see the following video: https://goo.gl/tUpWyq

**Comment by wearenocomputer** [comment]
Made the vertical space between items smaller, reducing the amount of chance this will happen.
Note: this only applies to the first song-selection screen...

**Comment by jonathanschaefferhookqa** [comment]
This can still happen on very small browser sizes, but this is most likely an edge case.

![screen shot 2018-06-15 at 3 17 17 pm](https://user-images.githubusercontent.com/14283709/41491639-3d7233f4-70af-11e8-88e6-8ff82ea8d61f.png)
![screen shot 2018-06-15 at 3 17 11 pm](https://user-images.githubusercontent.com/14283709/41491640-3d8a1668-70af-11e8-8f46-4ce4c500fea3.png)

**Comment by wearenocomputer** [comment]
@jeankcha 
Please advice...

**Comment by jeankcha** [comment]
@wearenocomputer Very edge case. No need to spend time on it.
