### ISSUE TITLE
Mobile Landscape Mode - Audio toggle overlaps the left vertical label

### ISSUE THREAD

**Issue by joeyqa** [tooldigital/pandora-sly-p2#3]
The volume is too close to the side label when the device is turned into landscape orientation when the browser has more than one tab

**Expected Result:**
- Adjust the Audio Toggle's position

**Browser / Device info:**
- iPad 4 (10.3.3)- Safari 
- Pixel XL (7.1.2)  - Chrome 66

**URL:**
- http://soundslikeyoudev.seethroughlab.com/#!

**Steps:**
1. Load the URL.
2. Add an extra tab then return to Pandora page.
3. Rotate the device to landscape orientation.
4. Verify that the Audio Toggle overlaps the side label.

Please see the attached screenshot(s): https://goo.gl/CdQdyg

**Comment by wearenocomputer** [comment]
Please r-test/validate...

**Comment by jonathanschaefferhookqa** [comment]
This is fixed on the iPad however I'm seeing it on the Pixel 2 XL. Should this be fixed on large screen phones as well?

![screenshot_20180615-152130](https://user-images.githubusercontent.com/14283709/41491836-494e8672-70b0-11e8-81b4-51d99ba98769.png)

**Comment by wearenocomputer** [comment]
@jeankcha 
Should this be fixed on large screen phones as well?
Also... what's the market share/adoption % of the Pixel 2 XL?

**Comment by jeankcha** [comment]
@wearenocomputer Not sure what the market share of the 2XL is, but an attemp to be fixed on large-screened phones would be great. Not priority 1, though.

**Comment by wearenocomputer** [comment]
Please look closely to the screenshot of the Pixel 2 XL. You will see that there's simply not enough screen estate to resolve this properly. Same remarks as issue #8 (overlapping content on smartphones in Landscape mode).

A quick-win would be to hide the audio control on smartphones in landscape mode, but  not sure if that's something we want. US market-share for Google devices (all of them, so not just the Pixel 2 XL) is about 1.7% (http://gs.statcounter.com/vendor-market-share/mobile/united-states-of-america)

Seeing the above, we're proposing to close.
@jeankcha Please advice...

**Comment by jeankcha** [comment]
Let's not fix. I prefer not to hide audio control on all smartphones in landscape.
