### ISSUE TITLE
Your Info - Continue button and label has inconsistent link

### ISSUE THREAD

**Issue by joeyqa** [tooldigital/pandora-sly-p2#4]
When the user is finished filling up the form, notice that when the user clicks the "Continue" button it directs the user to the "Your Mood" section while on the other hand when the user clicks the "Continue" button label directs the user to the "Your Song" section.

**Expected Result:**
- The links of the "Continue" button and "Continue" button label must be the same.

**Browser / Device info:**
- All desktop browsers

**URL:**
- http://soundslikeyoudev.seethroughlab.com/#!/your-info

**Steps:**
1. Load the URL.
2. Proceed to the "Your Info" section and fill the form.
3. Verify that when the user clicks the "Continue" button it directs them to the "Your Mood" section but if the user clicks the "Continue" button label it directs them to the "Your Song" section.

Please see the following video: https://goo.gl/SJVvR3

**Comment by wearenocomputer** [comment]
Please re-test/validate again...

**Comment by jonathanschaefferhookqa** [comment]
Verified Fixed.
