### ISSUE TITLE
Your Custom Song - Console throws a POST error

### ISSUE THREAD

**Issue by joeyqa** [tooldigital/pandora-sly-p2#5]
After going through the process of selecting moods and songs, notice on the song generation, the console throws a POST error on some song and mood combinations. For example, when the user selects every first item of each song lists.

Note: On other browsers, the page just freezes on the loading page and has no error in the console.

**Expected Result:**
- The user should able to generate a song by selecting any mood and song combinations.

**Browser / Device info:**
- Windows 10 - Chrome 67
- Macbook 10.13 - Chrome 67

**URL:**
- http://soundslikeyoudev.seethroughlab.com/#!/your-info

**Steps:**
1. Load the URL.
2. Go through the process up to the song selection screens.
3. Select every 1st item on the list.
4. Verify that after selecting the songs, the console throws a POST error.

Please see the following video: https://goo.gl/SSbRSS

**Comment by jeffcrouse** [comment]
@wearenocomputer It looks like this happens because sometimes I receive an empty "choices" array, which means I can't determine the genre. I now check for this and send a more descriptive error message, but any ideas why I might not receive any "choices"?

**Comment by wearenocomputer** [comment]
Ok, there were a couple of things going wrong here...
- One could bypass the 'moods'-view, resulting in no-data being send to the API
- Selecting every first song resulted in an empty 'choices' array being send to the API

It's very likely that the combo of those 2 issues was causing errors/nothing being generated.
Fixes for both issues have been deployed at http://soundslikeyoudev.seethroughlab.com

@jeffcrouse console.logging every API-call now

Please clear cache & re-test/validate...

**Comment by jonathanschaefferhookqa** [comment]
Not seeing this issue when trying this scenario again, closing.
