### ISSUE TITLE
Your Info - Text field doesn't have a character limit

### ISSUE THREAD

**Issue by joeyqa** [tooldigital/pandora-sly-p2#6]
Notice that upon filling up the text field, the user is able to enter a huge amount of characters.

**Expected Result:**
- Every text field should have max character length.

**Browser / Device info:**
- All browsers

**URL:**
- http://soundslikeyoudev.seethroughlab.com/#!/your-info

**Steps:**
1. Load the URL.
2. Fill up the text field.
3. Verify that there is no character limit on the text field.

Please see the attached screenshot(s):  https://goo.gl/ZVKsdA

**Comment by wearenocomputer** [comment]
Correct, text-fields have no limitations as:
- this was not requested
- is also the case on the v1

@jeankcha Please advice... 
Do you want me to implement this?
If so, how many characters do we want?

**Comment by jeankcha** [comment]
@wearenocomputer If that's the case in V1, let's leave it as is. Thanks.

**Comment by wearenocomputer** [comment]
We needed this for backend purposes as well, so I've added a max-length of 50 characters on firstname and lastname
