### ISSUE TITLE
iPhone 7+ | Landscape | Your Summary - Misaligned content

### ISSUE THREAD

**Issue by joeyqa** [tooldigital/pandora-sly-p2#7]
After creating the custom song notice that when the user proceeds to the "Your Summary" section the "Pitch Shift" and "Tempo Shift" content are misaligned.

**Expected Result:**
- Adjust the placement of the "Pitch Shift" and "Tempo Shift" content.

**Browser / Device info:**
- iPhone 7+ (11.3) - Safari, Chrome 67

**URL:**
- http://soundslikeyoudev.seethroughlab.com/#!/your-custom-song

**Steps:**
1. Load the URL.
2. Complete your custom song.
3. Proceed to the "Your Summary" section.
4. Verify that there is misaligned Content.

Please see the attached screenshot(s): https://goo.gl/yCgWBn

**Comment by wearenocomputer** [comment]
Please re-test/validate...

**Comment by lfm5002** [comment]
This is verified as fixed
